name: Randomly Select True or False Pages

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  switch-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Randomly Select Page
      id: select
      run: |
        RANDOM_NUMBER=$(( RANDOM % 2 ))
        if [ "$RANDOM_NUMBER" -eq 0 ]; then
          echo "page=true.html" >> $GITHUB_ENV
        else
          echo "page=false.html" >> $GITHUB_ENV
        fi

    - name: Update index.html with the selected page
      run: |
        SELECTED_PAGE=${page}
        echo "Selected page: $SELECTED_PAGE"
        current_page=$(cat index.html)

        echo "Current page: $current_page"

        if [[ "$current_page" != *"$SELECTED_PAGE"* ]]; then
          echo "Updating index.html to $SELECTED_PAGE"
          cp $SELECTED_PAGE index.html

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html

          if ! git diff --cached --exit-code; then
            git commit -m "Switched to $SELECTED_PAGE"
            git push
          else
            echo "No changes to commit."
          fi
        else
          echo "No change needed."
        fi
